ALTER TABLE devices
  ADD COLUMN IF NOT EXISTS beacon_enabled BOOLEAN NOT NULL DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS beacon_interval_min INTEGER NOT NULL DEFAULT 15,
  ADD COLUMN IF NOT EXISTS beacon_distance_km DOUBLE PRECISION NOT NULL DEFAULT 1.0;
