ALTER TABLE devices
  ADD COLUMN IF NOT EXISTS beacon_mode TEXT NOT NULL DEFAULT 'normal',
  ADD COLUMN IF NOT EXISTS beacon_batch_size INTEGER NOT NULL DEFAULT 50,
  ADD COLUMN IF NOT EXISTS beacon_batch_max_wait_min INTEGER NOT NULL DEFAULT 120,
  ADD COLUMN IF NOT EXISTS beacon_normal_send_min INTEGER NOT NULL DEFAULT 60;
